coverage:
  precision: 2
  round: down
  range: '70...100'

  status:
    project:
      default:
        target: 75%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 75%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: 'reach,diff,flags,tree'
  behavior: default
  require_changes: false

ignore:
  - 'node_modules/**/*'
  - 'dist/**/*'
  - 'coverage/**/*'
  - 'test/**/*'
  - '**/*.test.*'
  - '**/*.spec.*'
  - '**/*.config.*'
  - '**/types/**'
  - 'bin/**/*'
  - 'src/index.ts'
  - 'src/cli/run.ts'
  - 'src/cli/exit-code.ts'
  - 'src/modules/testing/templates/**/*'

flags:
  unittests:
    paths:
      - src/
    carryforward: true
